global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'vault-exporter'
    static_configs:
      - targets: ['vault-exporter:8080']
    scrape_interval: 10s
    metrics_path: /metrics

  - job_name: 'hardhat-node'
    static_configs:
      - targets: ['hardhat-node:8545']
    scrape_interval: 30s
    metrics_path: /metrics